language: c
os:
  - windows
compiler:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - SCIPY_VER="scipy>=0.18.0" 
matrix:
  fast_finish: true
notifications:
  email: false
install:
  - conda update conda
  - conda info -a
  - conda create -q -n test-environment python=$CC numpy scipy pandas matplotlib pip pytest sympy
  - source activate test-environment
  - conda install conda
  - python setup.py -q install
script:
  - cd tests
