language: python
python:
  - '3.8'
  - '3.7'
  - '2.7'

jobs:
  include:
    - python: '3.8' # this is not strictly necessary
      env: EXTRA_TESTS=true
    - python: '3.7'
      env: EXTRA_TESTS=true

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $ {{ secrets.chemsys1 }}  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
